"""initial schema

Revision ID: db92c6508a50
Revises: 
Create Date: 2026-04-11 14:22:50.614755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db92c6508a50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_bands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('taco_index_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_value', sa.Integer(), nullable=False),
    sa.Column('band_label', sa.String(length=50), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taco_index_history_calculated_at'), 'taco_index_history', ['calculated_at'], unique=False)
    op.create_table('tweets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('tweet_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_tweet_id'), 'tweets', ['tweet_id'], unique=True)
    op.create_table('tweet_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tweet_id', sa.UUID(), nullable=False),
    sa.Column('llm_score', sa.Integer(), nullable=False),
    sa.Column('keyword_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    # ### end Alembic commands ###
    op.execute("""
        INSERT INTO index_bands (id, label, min_score, max_score, color, description) VALUES
        (gen_random_uuid(), 'Extreme Bearish', 0,  20,  '#FF4444', 'Trump이 시장에 극도로 부정적인 발언 중'),
        (gen_random_uuid(), 'Bearish',         21, 40,  '#FF8C00', 'Trump 발언이 시장에 부정적'),
        (gen_random_uuid(), 'Neutral',         41, 60,  '#FFD700', 'Trump 발언이 시장에 중립적'),
        (gen_random_uuid(), 'Bullish',         61, 80,  '#32CD32', 'Trump 발언이 시장에 긍정적'),
        (gen_random_uuid(), 'Extreme Bullish', 81, 100, '#008000', 'Trump이 시장에 극도로 긍정적인 발언 중')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM index_bands")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_scores')
    op.drop_index(op.f('ix_tweets_tweet_id'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_index(op.f('ix_taco_index_history_calculated_at'), table_name='taco_index_history')
    op.drop_table('taco_index_history')
    op.drop_table('index_bands')
    # ### end Alembic commands ###
